### ISSUE TITLE
[DOC] Informations on non talos hosts

### ISSUE THREAD

**Issue by mbl-35** [ahinko/home-ops#2140]
Hi Peter, 
Thanks for your great job ! 
I try to rebuild your environment at home but could not find any informations for your hosts pikvm, pinut and zwave-coordinator.
In the ansible part, we can find how to install these hosts, but nothing about used os and hardware (suppose this are rpi-4b ?), and ops upgrading...
Could you add a dedicated part for these hosts ?
Thanks

Math

**Comment by ahinko** [comment]
Hi, it's really fun to hear that others has a use for this repo. You have a valid point and I will definitely add some docs about these hosts. But to give you an idea (and to try to answer your questions):

* PiKVM is a RPi4 with a POE hat and a HDMI to CSI-2 bridge. It's running PiKVM-OS and it's connected to a TESmart 8 Port KVM Switch.
* pihut is a RPi4 with a POE hat running Ubuntu 23.04 and it's connected to two Eaton 3S UPS.
* zwave-coordinator is a RPi Zero W Rev 1.1 with a POE hat running Raspbian 11 and a Zwave-stick connected through USB. ser2net is installed so that Zwave-JS can connect to the USB stick.

I haven't set up any gitops flow to keep them up to date for various reasons and I also tend to not wanting to mess with these because I heavily rely on them being online:
* I haven't found a good way to do this for PiKVM and to quote the docs: "This is ONLY recommended if you need a feature...".
* The zwave-coordinator doesn't have many things running on it but an `apt update` should be enough but I would only do that if I absolutely need and when I have time to fix any issues that might occur. My smart home relies heavily on this host being online.
* pinut on the other hand could have some gitops in place for at least updating the Docker image used for the two containers. I haven't thought much about it since NUT is such a mature project with barely any updates. I might add this sometime in the future.

Let me know if you have any more questions and I will do my best to answer!
