### ISSUE TITLE
EMQX Operator Woes

### ISSUE THREAD

**Issue by onedr0p** [ahinko/home-ops#2925]
Hi 👋🏼 

I was looking at your emqx operator deployment, however I cannot even get a simple config to work... do you have any insights there?

https://github.com/onedr0p/home-ops/tree/main/kubernetes/main/apps/database/emqx

I raised an issue upstream too
https://www.github.com/emqx/emqx-operator/issues/1036

You think a basic emqx resource would just work 😞

**Comment by ahinko** [comment]
Hi @onedr0p 

I deployed a EMQX test cluster and I see the same issue you are seeing. 

I also noticed that no svc are created. My regular/production EMQX cluster has three services:

```
emqx-dashboard                                     ClusterIP      10.109.165.6     <none>           18083/TCP                                      49d
emqx-headless                                      ClusterIP      None             <none>           4370/TCP,5369/TCP                              49d
emqx-listeners                                     ClusterIP      10.109.30.70     <none>           8883/TCP,1883/TCP,8083/TCP,8084/TCP            49d
```

I've had multiple issues with EMQX over a long period of time and I switched to Mosquitto for a while. I also recall having a similar issue to this one before and if I remember correctly it had to do with health checks that either returned false by the pods or maybe it was that the operator(?) wasn't able to connect to the endpoint. I'm not sure. The only reason I'm coming back to EMQX is the high availability feature. If I could have HA with for example Mosquitto I would leave EMQX in a heartbeat. Every time there is an update I'm hesitant to update due to the history of issues.

It's not a real solution to the problem but it might be interesting to try an older version of the operator and maybe the core pods. When I switched from Mosquitto to EMXQ the last time I used version 2.2.14 of the operator and version 5.5.0 of the core pods. See commit https://github.com/ahinko/home-ops/commit/f279954420414a5401dd740db54936f05edb96f5

My guess would be that the issue is related to having no svc for the core pods, especially the `emqx-dashboard` one with port 18083 because I think the health checks are done on that port.

One more thing. You might also need to have this in your cluster config:
```yaml
      dashboard {
        listeners.http {
            bind: 18083
        }
      }
```

It doesn't seem to help when I tested now so its not the main issue but you might need this to make the pods listen on that port.

I'm sorry that I can't be of more help.

**Comment by onedr0p** [comment]
Thanks for the info, I have struggled with emqx and updating it in the past breaking my home automation and it's good to know not much has improved since then :/

It seems like their operator is not well tested, or just breaks with using Flux or it doesn't like Cilium.

**Comment by ahinko** [comment]
Version 2.2.20 of the operator fixes the issue.

**Comment by onedr0p** [comment]
Perfect, I'll get around to trying it later today. Thanks!
